import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NonLoginNavbar from "@/components/NonLoginNavbar"; 
import ClientNavbar from "@/components/ClientNavbar";
import FrontDeskNavbar from "@/components/FrontDeskNavbar";
import DoctorNavbar from "@/components/DoctorNavbar";
import NurseNavbar from "@/components/NurseNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NonLoginNavbar/>
        
        <main className="min-h-screen">
        {children}
        </main>
        
      </body>
    </html>
  );
}
